version: '2.5'
services:
  client:
      build:
        dockerfile: Dockerfile.dev
        context: ./angular-client
      volumes:
        #In questo modo dico a docker di usare la cartella del container /app/node_modules come volume
        #La cartella locale node_modules non verrà più copiata
        - /app/node_modules 
        #Qui mappa tutto il contenuto della cartella locale client nella cartella app dell'immagine
        #Ricorda che la WORKDIR dell'immagine è la cartella app
        - ./angular-client:/app
      ports:
        - 4200:4200
      networks:
      - shared-network
  server:
      build:
        dockerfile: Dockerfile.dev
        context: ./express-server
        args:
          - NODE_ENV=development
      volumes:
        - ./express-server:/app
      ports:
        - 3000:3000
      networks:
      - shared-network

networks:
  shared-network: