# Stage 1: Compile and Build angular codebase

# Use latest node image as the base image
FROM node:16-alpine as builder

# Set the working directory
WORKDIR '/app' 

# Install all the dependencies 
COPY ./package.json ./
RUN npm install

# Install Angular CLI 12
RUN npm install --global @angular/cli@12

# Add the source code to app
COPY . .

# env
ARG GITPOD_WORKSPACE_URL=${GITPOD_WORKSPACE_URL:-""}
ENV NG_APP_GITPOD_WORKSPACE_URL=${GITPOD_WORKSPACE_URL}
ENV NG_APP_SERVER_PORT=3000

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]
