FROM node:16-alpine

WORKDIR '/app'

COPY ./package.json ./
RUN npm install
RUN npm install --global nodemon

COPY . .

ARG NODE_ENV=${NODE_ENV:-""}
ENV NODE_ENV=${NODE_ENV}

EXPOSE 3000

CMD ["npm", "start"]